# GET http://localhost:3000/products
# ###
# GET http://localhost:3000/products/60f030fbb02de644b075fd2c

@uri = http://localhost:3000/
###
GET {{uri}}products
###
GET {{uri}}products/60f030fbb02de644b075fd2c
###
POST {{uri}}products
# 如果是ajax库可能不需要以下这个请求头
Content-Type: application/json

# 表示接下来发送json数据了
# {
#   "title":"产品4"
# }
{
  "title":"产品5"
}



###
PUT {{uri}}products/60f3ef1d8962e20d14099e56
Content-Type: application/json

# 表示接下来发送json数据了
# {
#   "title":"产品55"
# }
{
  "title":"产品5"
}



###
# 删除产品5
# DELETE {{uri}}products/60f3ef1d8962e20d14099e56
# 删除产品4
DELETE {{uri}}products/60f3e390eca0a72dd0923f98
## 不用发送请求参数